server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  application:
    name: QUIZ-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

